# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [13]:
%tensorflow_version 2.x

In [12]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [14]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [15]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
from sklearn import datasets

In [17]:
iris = datasets.load_iris()


## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [18]:
X = iris.data
y = iris.target

In [19]:
print(X[0,:])

[5.1 3.5 1.4 0.2]


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [52]:
from keras.utils import to_categorical

y_train = to_categorical(y_train, num_classes=3)
y_test  = to_categorical(y_test, num_classes=3)



In [53]:
print(y_test)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


## Question 5

### Initialize a sequential model
- Define a sequential model

In [54]:
model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [55]:
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(3, input_shape=(4,), activation='softmax'))

In [56]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [57]:
#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [58]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


- There is 1 layer, 3 outputs.
- Number of input is 4 
- Parammeters (3 output neuron * 4 inputs) + 3 bias for each neuron = 15

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [60]:
model.fit(X_train, y_train,
          validation_data=(X_test, y_test), 
          epochs=100,
          batch_size = 5
         )

Epoch 1/100
23/23 [==============================] - 0s 5ms/step - loss: 0.5557 - accuracy: 0.7321 - val_loss: 0.5166 - val_accuracy: 0.7368
Epoch 2/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5584 - accuracy: 0.7589 - val_loss: 0.4820 - val_accuracy: 0.7895
Epoch 3/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5443 - accuracy: 0.7321 - val_loss: 0.4712 - val_accuracy: 0.8158
Epoch 4/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5255 - accuracy: 0.7500 - val_loss: 0.4648 - val_accuracy: 0.7368
Epoch 5/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5150 - accuracy: 0.7589 - val_loss: 0.4585 - val_accuracy: 0.8158
Epoch 6/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5176 - accuracy: 0.7857 - val_loss: 0.4574 - val_accuracy: 0.8158
Epoch 7/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5063 - accuracy: 0.8214 - val_loss: 0.4594 - val_accuracy: 0.7368
Epoch 8/100
2

## Question 10

### Make predictions
- Predict labels on one row

In [64]:
model.predict(X_test[:1])

array([[0.01346575, 0.6065935 , 0.37994084]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [65]:
y_test[0:1]

array([[0., 1., 0.]], dtype=float32)

Predicted label and actual label is same.




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [66]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [67]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [68]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [ ]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [107]:
import pandas as pd
dfprice = pd.read_csv("/content/prices.csv")

In [108]:
dfprice.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [109]:
dfprice.drop(["date", "symbol"],axis=1, inplace=True)

In [110]:
dfprice.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [111]:
dfprice = dfprice.head(1000)

In [112]:
dfprice.shape


(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [113]:
X = dfprice[["open","close","low","high"]]
y = dfprice[["volume"]]/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [114]:
import numpy as np

X = np.asarray(X, dtype="float32")
y = np.asarray(y, dtype="float32")

## Question **6**

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize


In [115]:
X = tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [124]:
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [125]:
def prediction(X, W, b):
    xw_matmul = tf.matmul(X, W)
    y = tf.add(xw_matmul, b)
    
    return y


### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [126]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    actloss = tf.reduce_mean(sqr)
    
    return actloss


## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [127]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - (learning_rate*dw)
    b = b - (learning_rate*db)
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [128]:
for i in range(100):
    
    w, b = train(X, y, w, b)
    print('Current Loss on iteration', i, loss(y, prediction(X, w, b)).numpy())

Current Loss on iteration 0 236.16806
Current Loss on iteration 1 235.09369
Current Loss on iteration 2 234.06195
Current Loss on iteration 3 233.07103
Current Loss on iteration 4 232.11938
Current Loss on iteration 5 231.20544
Current Loss on iteration 6 230.32771
Current Loss on iteration 7 229.48482
Current Loss on iteration 8 228.67525
Current Loss on iteration 9 227.89775
Current Loss on iteration 10 227.15108
Current Loss on iteration 11 226.434
Current Loss on iteration 12 225.74532
Current Loss on iteration 13 225.08392
Current Loss on iteration 14 224.4487
Current Loss on iteration 15 223.8387
Current Loss on iteration 16 223.25285
Current Loss on iteration 17 222.6902
Current Loss on iteration 18 222.14984
Current Loss on iteration 19 221.63089
Current Loss on iteration 20 221.13252
Current Loss on iteration 21 220.65384
Current Loss on iteration 22 220.19418
Current Loss on iteration 23 219.75272
Current Loss on iteration 24 219.32875
Current Loss on iteration 25 218.92157
C

### Observe values of Weight
- Print the updated values

In [129]:
#Check Weights and Bias
print('Weights:\n', w.numpy())

Weights:
 [[0.0194333 ]
 [0.01969695]
 [0.01937149]
 [0.01976266]]


### Observe values of Bias
- Print the updated values

In [130]:
print('Bias:\n',b.numpy())

Bias:
 [4.608607]
